# Conda environment for lassiterdc-utils
#
# Create:   conda env create -f environment.yaml
# Activate: conda activate lassiterdc_utils
# Update:   conda env update -f environment.yaml
# Remove:   conda deactivate && conda env remove -n lassiterdc_utils
name: lassiterdc_utils
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # development tools
  - ruff
  - pytest
  - coverage
  - ipdb
  - pip:
      - -e .
